### ISSUE TITLE
swap: use new builds of swap.war and cdx-server.war

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/swap#30]
- [x] new swap build is functional  (#8 - ish)  <-- code may be okay now, but war isn't working right -- `dist` maven build is probably implicated.
- [ ] pass UAT testing of new builds (#26) 
- [ ] Update puppet to use new builds from sul-dlss/swap  instead of from  sul-dlss/openwayback (see also #7).    (see below)
Lastly:
- [ ] cdx-server: robot suite should use same version as swap code: sul-dlss/was_robot_suite/issues/77
The puppet changes are minimal:
(in all `hieradata/node/sul-swap-XXX.stanford.edu.eyaml`)

```
@@ -64,10 +65,10 @@ profile::tomcat:
       java_options: '-Xms3G -Xmx3G -XX:PermSize=256m -XX:MaxPermSize=768m -server -Djava.awt.headless=true'
   webapps:
     openwayback:
-      war_source: 'https://jenkinsqa.stanford.edu/artifacts/wayback-webapp/target/openwayback-2.0.1-SNAPSHOT.war'
+      war_source: 'https://jenkinsqa.stanford.edu/artifacts/dist/target/swap-distrib-2.0.0.war'
       warfile: 'ROOT.war'
     cdx:
-      war_source: 'https://jenkinsqa.stanford.edu/artifacts/wayback-cdx-server/target/openwayback-cdx-server-2.0.1-SNAPSHOT.war'
+      war_source: 'https://jenkinsqa.stanford.edu/artifacts/upstream-cdx-server/target/openwayback-cdx-server-2.0.0.war'
       warfile: 'cdx-server.war'
```

**Comment by ndushay** [comment]
progress report:   I *thought* I had all the localizations ported over for ```wayback-core``` and ```wayback-webapp``` (and we have no changes for ```wayback-cdx-server```), but the new swap war file created is not working right.  Currently seeing the following in tomcat logs (`catalina.out`):

```
Aug 10, 2017 11:52:02 AM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter RequestFilter
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fastArchivalSAXDelegator' defined in URL [file:/usr/share/tomcat/webapps/ROOT/WEB-INF/ArchivalUrlReplay.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:585)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:84)
	at org.archive.wayback.util.webapp.SpringReader.readSpringConfig(SpringReader.java:59)
	at org.archive.wayback.util.webapp.RequestFilter.loadRequestMapper(RequestFilter.java:175)
	at org.archive.wayback.util.webapp.RequestFilter.init(RequestFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4958)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5652)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.archive.wayback.archivalurl.StandardAttributeRewriter.loadRules(StandardAttributeRewriter.java:239)
	at org.archive.wayback.archivalurl.StandardAttributeRewriter.init(StandardAttributeRewriter.java:202)
	at org.archive.wayback.archivalurl.FastArchivalUrlReplayParseEventHandler.init(FastArchivalUrlReplayParseEventHandler.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1544)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
	... 30 more
```

**Comment by ndushay** [comment]
progress report - it's working!  puppet branch `ndushaySwap` has been deployed on `sul-swap-stage`
